### PR TITLE
Volume

### PR DESCRIPTION
**Pull request by juliengk**

### CODE REVIEW

**Comment by nenne70** [comment]
Will that solution also symlinks? That was a reason I checked the full path.

**Comment by juliengk** [comment]
in the container running the plugin there is no access to the FS that the plugin is validating

**Comment by nenne70** [comment]
But the check is done by hbm not inside the container. At least what I remember I ensure that the host path doesn’t contain “illegal path”, the path that is mounted inside the container is not checked.

At least it passed my verification that I can not use ../ or symlinks on the real filesystem.

**Comment by juliengk** [comment]
the plugin does not always run on the host. I understand that most if not all the time you install hbm with the rpm package. But hbm can also be used as a container https://hub.docker.com/r/kassisol/hbm.

**Comment by nenne70** [comment]
Yes I understand :)

**Pull request merged**
